FROM node:14-alpine

RUN npm -v
RUN node -v

RUN npm install -g nodemon


# Bundle APP files
WORKDIR /app

#handle package installation
COPY package*.json /app/
ENV NPM_CONFIG_LOGLEVEL verbose
#RUN npm install
## installs gyp to build dependencies and delete it afterward (required for bcrypt)
RUN apk add --no-cache --virtual .gyp python make g++ && npm install && apk del .gyp


#copy project files
COPY . .

EXPOSE 8080
